
--STG产品规格订单(3.0)
CREATE EXTERNAL TABLE IF NOT EXISTS STG_ORD_PROD  (
   PROD_ORDER_ID        STRING,
   CUST_ORDER_ID        STRING,
   BUSIOPER_ORDER_ID    STRING,
   PROD_SPEC_ID         STRING,
   PROD_INST_ID         STRING,
   PROD_ROLE_ID         STRING,
   NEW_PROD_ORDER_ID    STRING,
   OFFER_ID             STRING,
   BRAND_ID             STRING,
   CUST_ID              STRING,
   ACCT_ID              STRING,
   PAY_TYPE             STRING,
   BILL_ID              STRING,
   SUB_BILL_ID          STRING,
   MAIN_PROD_INST_ID    STRING,
   BILL_START_DATE      STRING,
   STATE                STRING,
   ORDER_STATE          STRING,
   OS_STATUS            STRING,
   OUTLINE_FLAG         STRING,
   OWE_AMOUNT           STRING,
   PASSWORD_TYPE        STRING,
   PASSWORD             STRING,
   CONT_ID              STRING,
   ADDRESS_ID           STRING,
   VALID_TYPE           STRING,
   USER_STATE           STRING,
   DONE_CODE            STRING,
   BOOK_HOME_DATE       STRING,
   BOOK_OPEN_DATE       STRING,
   REGION_ID            STRING,
   SALE_ORG_ID          STRING,
   OWN_CORP_ORG_ID      STRING,
   OWN_ORG_ID           STRING,
   CREATE_OP_ID         STRING,
   CREATE_ORG_ID        STRING,
   CREATE_DATE          STRING,
   DONE_DATE            STRING,
   VALID_DATE           STRING,
   EXPIRE_DATE          STRING,
   OP_ID                STRING,
   ORG_ID               STRING,
   REMARK               STRING,
   EXT1                 STRING,
   EXT2                 STRING,
   EXT3                 STRING,
   EXT4                 STRING,
   EXT5                 STRING,
   EXT6                 STRING,
   USER_NAME            STRING,
   USER_PROP            STRING,
   USER_GROUP           STRING,
   VIP_FLAG             STRING,
   VIP_PROP             STRING,
   BODER_FLAG           STRING,
   SUBSIDY_FLAG         STRING,
   SUBSIDY_PROP         STRING,
   DEGREE_FLAG          STRING,
   FIRST_USE_DATE       STRING,
   ACCESS_MODE          STRING,
   USER_TYPE_ID         STRING,
   INSTALL_ADDR_ID      STRING,
   INSTALL_ADDR_NAME    STRING,
   LOGIN_NAME           STRING,
   TV_NUMBER            STRING,
   DATA_SOURCE_CD       STRING,
   ETL_CYCLE            STRING,
   ETL_DATE             STRING
)PARTITIONED BY (PT_TIME STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE
LOCATION '/asiainfo/hive/STG/stg_ord_prod';

